language: objective-c
osx_image: xcode9.2

script:
- set -o pipefail
- xcodebuild test -workspace WTCalendarView.xcworkspace -scheme CalendarViewExample -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
