language: objective-c
osx_image: xcode9.2

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild -workspace WTCalendarView.xcworkspace -list
- xcodebuild build -workspace WTCalendarView.xcworkspace -scheme WTCalendarView -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- xcodebuild build -workspace WTCalendarView.xcworkspace -scheme WTCalendarView -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
